name: dowell_app
description: ""

publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  
  # State Management (Riverpod - easier than Provider)
  flutter_riverpod: ^2.4.9

   # Image Picking
  image_picker: ^1.0.4
  
  # Other utilities
  cached_network_image: ^3.3.0
  path_provider: ^2.1.0
  
  # Form validation
  form_validator: ^1.0.0

  # Phone validation
  phone_form_field: 10.0.17
  
  # Loading indicators
  loading_animation_widget: ^1.2.0

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dowell_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/dowell_logo.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/dowell_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/dowell_logo.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"
    image: assets/images/dowell_logo.png

