// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjXFTl3alfqVVl_vFXnTxq2nKhhwIur5w',
    appId: '1:12126775970:web:d947fa0082d965e158c5fb',
    messagingSenderId: '12126775970',
    projectId: 'dowell-pest-control',
    authDomain: 'dowell-pest-control.firebaseapp.com',
    storageBucket: 'dowell-pest-control.firebasestorage.app',
    measurementId: 'G-VFB839TQV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKOdYRfsvDEpphn5Yo_R-cLEG74kxsYg',
    appId: '1:12126775970:android:e00994e0d9e2d9e358c5fb',
    messagingSenderId: '12126775970',
    projectId: 'dowell-pest-control',
    storageBucket: 'dowell-pest-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBqdsqOSfRX8Yy8EDOArNM1_my-VQ1Po',
    appId: '1:12126775970:ios:951f17ff42427bdb58c5fb',
    messagingSenderId: '12126775970',
    projectId: 'dowell-pest-control',
    storageBucket: 'dowell-pest-control.firebasestorage.app',
    iosClientId: '12126775970-sivbhkl18234f13u61tq7d972jtv0dkp.apps.googleusercontent.com',
    iosBundleId: 'com.dowell.pestcontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiBqdsqOSfRX8Yy8EDOArNM1_my-VQ1Po',
    appId: '1:12126775970:ios:951f17ff42427bdb58c5fb',
    messagingSenderId: '12126775970',
    projectId: 'dowell-pest-control',
    storageBucket: 'dowell-pest-control.firebasestorage.app',
    iosClientId: '12126775970-sivbhkl18234f13u61tq7d972jtv0dkp.apps.googleusercontent.com',
    iosBundleId: 'com.dowell.pestcontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjXFTl3alfqVVl_vFXnTxq2nKhhwIur5w',
    appId: '1:12126775970:web:a4f73c98be7b832158c5fb',
    messagingSenderId: '12126775970',
    projectId: 'dowell-pest-control',
    authDomain: 'dowell-pest-control.firebaseapp.com',
    storageBucket: 'dowell-pest-control.firebasestorage.app',
    measurementId: 'G-VVDWZBZFGH',
  );
}
